package com.techwatch.techwatchbackend.devices.domain.model.aggregates;

import com.techwatch.techwatchbackend.devices.domain.model.commands.StartSimulationSessionCommand;
import com.techwatch.techwatchbackend.devices.domain.model.entities.DeviceAction;
import com.techwatch.techwatchbackend.devices.domain.model.entities.UsageDataRecord;
import com.techwatch.techwatchbackend.devices.domain.model.events.SimulationSessionEndedEvent;
import com.techwatch.techwatchbackend.devices.domain.model.events.UsageDataGeneratedEvent;
import com.techwatch.techwatchbackend.devices.domain.model.valueobjects.DeviceId;
import com.techwatch.techwatchbackend.devices.domain.model.valueobjects.PropertyId;
import com.techwatch.techwatchbackend.devices.domain.model.valueobjects.SessionStatus;
import com.techwatch.techwatchbackend.devices.domain.model.valueobjects.UserId;
import com.techwatch.techwatchbackend.shared.domain.model.aggregates.AbstractDomainAggregateRoot;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * SimulationSession aggregate root.
 *
 * <p>
 * Represents a session in which a user simulates the operation of the devices of a property,
 * recording the actions executed ({@link DeviceAction}) and the usage data generated
 * ({@link UsageDataRecord}). Both are internal entities of this aggregate. No JPA or persistence
 * annotation is present here -- those concerns live exclusively in {@code SimulationSessionPersistenceEntity}.
 * </p>
 */
@Getter
public class SimulationSession extends AbstractDomainAggregateRoot<SimulationSession> {
    /**
     * The unique identifier for the simulation session.
     */
    @Setter
    private Long id;

    /**
     * The id of the user who owns the session.
     */
    @Setter
    private UserId userId;

    /**
     * The id of the property the session runs on.
     */
    @Setter
    private PropertyId propertyId;

    /**
     * The status of the session.
     */
    @Setter
    private SessionStatus status;

    /**
     * The moment the session started.
     */
    @Setter
    private LocalDateTime startedAt;

    /**
     * The moment the session ended, if it has ended.
     */
    @Setter
    private LocalDateTime endedAt;

    /**
     * The actions executed during the session.
     */
    private List<DeviceAction> actions;

    /**
     * The usage data records generated during the session.
     */
    private List<UsageDataRecord> usageData;

    /**
     * Default constructor for SimulationSession.
     * Initializes empty lists of actions and usage data.
     */
    public SimulationSession() {
        this.actions = new ArrayList<>();
        this.usageData = new ArrayList<>();
    }

    /**
     * Constructor for SimulationSession with a StartSimulationSessionCommand.
     * The session starts in the ACTIVE status with the current timestamp.
     * @param command The {@link StartSimulationSessionCommand}.
     */
    public SimulationSession(StartSimulationSessionCommand command) {
        this.userId = new UserId(command.userId());
        this.propertyId = new PropertyId(command.propertyId());
        this.status = SessionStatus.ACTIVE;
        this.startedAt = LocalDateTime.now();
        this.actions = new ArrayList<>();
        this.usageData = new ArrayList<>();
    }

    /**
     * Indicates whether the session is currently active.
     * @return true if the status is ACTIVE.
     */
    public boolean isActive() {
        return this.status == SessionStatus.ACTIVE;
    }

    /**
     * Ends the session, setting its status to ENDED and recording the end timestamp.
     *
     * <p>Registers a {@link SimulationSessionEndedEvent} so that the Analytics context can
     * automatically generate a consumption report for the session's period.</p>
     *
     * @return the updated SimulationSession instance.
     */
    public SimulationSession end() {
        this.status = SessionStatus.ENDED;
        this.endedAt = LocalDateTime.now();
        registerDomainEvent(new SimulationSessionEndedEvent(
                this.id, this.userId.userId(), this.propertyId.propertyId(), this.startedAt, this.endedAt));
        return this;
    }

    /**
     * Records an action executed against a device during the session, generating the corresponding
     * usage data and registering a {@link UsageDataGeneratedEvent} so that the Analytics context can
     * react to it.
     *
     * <p>The consumption value is computed by the application service (from the device rated power and
     * the action duration) and passed in, since it depends on the {@code Device} aggregate.</p>
     *
     * @param deviceId The id of the target device.
     * @param actionType The type of action.
     * @param parameterName The action parameter name, if any.
     * @param parameterValue The action parameter value, if any.
     * @param consumptionValue The consumption value generated by the action.
     * @param unit The unit of the consumption value.
     */
    public void recordAction(DeviceId deviceId, String actionType, String parameterName, String parameterValue,
                             Double consumptionValue, String unit) {
        var action = new DeviceAction(deviceId, actionType, parameterName, parameterValue);
        this.actions.add(action);
        var usage = new UsageDataRecord(deviceId, consumptionValue, unit);
        this.usageData.add(usage);
        registerDomainEvent(new UsageDataGeneratedEvent(
                this.userId.userId(),
                this.propertyId.propertyId(),
                deviceId.deviceId(),
                consumptionValue,
                unit,
                usage.getRecordedAt()));
    }

    /**
     * Replaces the list of device actions.
     * Used by the persistence assembler when reconstructing the aggregate.
     * @param actions The list of device actions.
     */
    public void setActions(List<DeviceAction> actions) {
        this.actions = actions == null ? new ArrayList<>() : actions;
    }

    /**
     * Replaces the list of usage data records.
     * Used by the persistence assembler when reconstructing the aggregate.
     * @param usageData The list of usage data records.
     */
    public void setUsageData(List<UsageDataRecord> usageData) {
        this.usageData = usageData == null ? new ArrayList<>() : usageData;
    }
}
